Improve type of Create
honestica/fhir.js pull request #5
Opened 2018-12-11 14:48 UTC by Arahir

2018-12-12 15:03 UTC, pierrickouw requested changes
On voudrait peut être repartir de `master` directement, histoire de repartir d'une base plus saine avec le repo originel. 
On peut monter (enfin descendre) la version `@types/fhir` du coup aussi pour les avoir à jour !

2018-12-12 15:03 UTC, pierrickouw commented on src/fhir.d.ts
>      function Create(content: { type: ResourceName, data: any }): Promise<{ data: any }>
On pourrait avoir `T` ici non à la place du `any` ?

2018-12-12 15:03 UTC, pierrickouw commented on src/fhir.d.ts
>      export interface QueryOptions {
On définit pas tout ce qui est possible ici: (il y a des `$or` par `exemple dans la doc fhir.js. Ca risque de rendre impossible l'utilisation du `search`. Je sais pas si on peut faire `$include` qui est de type `QueryOptions` puis d'autres propriétes en `any`. Quelque chose comme: https://www.typescriptlang.org/play/#src=interface%20Test%20%7B%0D%0A%20%20%20%20query%3A%20%7B%20other%3A%20'aaa'%20%7D%20%2C%0D%0A%20%20%20%20%5Bkey%3A%20string%5D%3A%20any%0D%0A%7D%0D%0A%0D%0A%0D%0Afunction%20t(v%3APartial%3CTest%3E)%20%7B%0D%0A%0D%0A%7D%0D%0A%0D%0At(%7B%20query%3A%20'4'%2C%20t%3A%20'3'%20%7D)

2018-12-28 15:37 UTC, Arahir commented
obsolete voir https://github.com/honestica/fhir.js/pull/7

2018-12-28 15:37 UTC, closed without merging